// Wire protocol between CoC2 server and agents (decision A1: full
// protobuf frames over WebSocket binary messages).
//
// Framing: every WS frame is self-describing by its opcode — TextMessage
// carries the legacy JSON Envelope, BinaryMessage carries WireEnvelope below.
// Negotiation: AgentHello declares proto_version; the server switches the
// connection to protobuf frames starting at hello_ack.
//
// Field-number discipline: never reuse or renumber fields after release.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: coc2/v1/wire.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WireEnvelope wraps a typed payload. payload is the serialization of the
// message named by type (e.g. "task_dispatch" -> Task).
type WireEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireEnvelope) Reset() {
	*x = WireEnvelope{}
	mi := &file_coc2_v1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireEnvelope) ProtoMessage() {}

func (x *WireEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireEnvelope.ProtoReflect.Descriptor instead.
func (*WireEnvelope) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *WireEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WireEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AgentHello struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token       string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hostname    string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os          string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch        string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	IpAddrs     []string               `protobuf:"bytes,6,rep,name=ip_addrs,json=ipAddrs,proto3" json:"ip_addrs,omitempty"`
	Tags        []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Fingerprint string                 `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Version     string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	ConnectedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	// proto_version declares the highest protobuf wire version the agent
	// understands (currently 1). Absent/0 keeps the legacy JSON protocol.
	ProtoVersion  uint32 `protobuf:"varint,11,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_coc2_v1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AgentHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentHello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentHello) GetIpAddrs() []string {
	if x != nil {
		return x.IpAddrs
	}
	return nil
}

func (x *AgentHello) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentHello) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AgentHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHello) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *AgentHello) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PendingTasks  []*Task                `protobuf:"bytes,3,rep,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_coc2_v1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HelloAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HelloAck) GetPendingTasks() []*Task {
	if x != nil {
		return x.PendingTasks
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_coc2_v1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MetricsReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UptimeSecs         int64                  `protobuf:"varint,3,opt,name=uptime_secs,json=uptimeSecs,proto3" json:"uptime_secs,omitempty"`
	CpuCount           int32                  `protobuf:"varint,4,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	Goroutines         int32                  `protobuf:"varint,5,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	ProcessMemoryBytes uint64                 `protobuf:"varint,6,opt,name=process_memory_bytes,json=processMemoryBytes,proto3" json:"process_memory_bytes,omitempty"`
	RootDiskTotalBytes uint64                 `protobuf:"varint,7,opt,name=root_disk_total_bytes,json=rootDiskTotalBytes,proto3" json:"root_disk_total_bytes,omitempty"`
	RootDiskFreeBytes  uint64                 `protobuf:"varint,8,opt,name=root_disk_free_bytes,json=rootDiskFreeBytes,proto3" json:"root_disk_free_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_coc2_v1_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsReport) GetUptimeSecs() int64 {
	if x != nil {
		return x.UptimeSecs
	}
	return 0
}

func (x *MetricsReport) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *MetricsReport) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *MetricsReport) GetProcessMemoryBytes() uint64 {
	if x != nil {
		return x.ProcessMemoryBytes
	}
	return 0
}

func (x *MetricsReport) GetRootDiskTotalBytes() uint64 {
	if x != nil {
		return x.RootDiskTotalBytes
	}
	return 0
}

func (x *MetricsReport) GetRootDiskFreeBytes() uint64 {
	if x != nil {
		return x.RootDiskFreeBytes
	}
	return 0
}

type Task struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// type is the executor kind, currently only "shell".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// command is bytes: shell input may contain arbitrary non-UTF-8 bytes.
	Command       []byte                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSecs   int32                  `protobuf:"varint,5,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_coc2_v1_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Task) GetTimeoutSecs() int32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_coc2_v1_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{6}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskAck) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type TaskCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCancel) Reset() {
	*x = TaskCancel{}
	mi := &file_coc2_v1_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCancel) ProtoMessage() {}

func (x *TaskCancel) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCancel.ProtoReflect.Descriptor instead.
func (*TaskCancel) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{7}
}

func (x *TaskCancel) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCancel) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskCancel) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type TaskResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId  string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status   string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// stdout/stderr are bytes: command output is arbitrary bytes and must not
	// be corrupted or rejected by UTF-8 validation (the legacy JSON transport
	// silently replaced invalid sequences with U+FFFD).
	Stdout        []byte                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_coc2_v1_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *TaskResult) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type FileTransferStart struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	AgentId    string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// direction is "upload" (server -> agent) or "download" (agent -> server).
	Direction      string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	LocalPath      string                 `protobuf:"bytes,4,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath     string                 `protobuf:"bytes,5,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Size           int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Offset         int64                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	ChunkSize      int32                  `protobuf:"varint,8,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,9,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	RequestedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileTransferStart) Reset() {
	*x = FileTransferStart{}
	mi := &file_coc2_v1_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferStart) ProtoMessage() {}

func (x *FileTransferStart) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferStart.ProtoReflect.Descriptor instead.
func (*FileTransferStart) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{9}
}

func (x *FileTransferStart) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileTransferStart) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FileTransferStart) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *FileTransferStart) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileTransferStart) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileTransferStart) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileTransferStart) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *FileTransferStart) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *FileTransferStart) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type FileTransferChunk struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Seq        int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// data is raw file bytes on the wire; the legacy JSON protocol transports
	// the same value base64-encoded, which this field eliminates.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferChunk) Reset() {
	*x = FileTransferChunk{}
	mi := &file_coc2_v1_wire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferChunk) ProtoMessage() {}

func (x *FileTransferChunk) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferChunk.ProtoReflect.Descriptor instead.
func (*FileTransferChunk) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{10}
}

func (x *FileTransferChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferChunk) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *FileTransferChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileTransferResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferResume) Reset() {
	*x = FileTransferResume{}
	mi := &file_coc2_v1_wire_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferResume) ProtoMessage() {}

func (x *FileTransferResume) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferResume.ProtoReflect.Descriptor instead.
func (*FileTransferResume) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{11}
}

func (x *FileTransferResume) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferResume) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileTransferResume) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// FileTransferCancel asks the peer to stop an in-flight transfer. The
// receiver confirms by completing the transfer with
// FileTransferDone{status: "canceled"}; the partial (.part) file is kept
// on both ends so a retry can resume.
type FileTransferCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferCancel) Reset() {
	*x = FileTransferCancel{}
	mi := &file_coc2_v1_wire_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferCancel) ProtoMessage() {}

func (x *FileTransferCancel) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferCancel.ProtoReflect.Descriptor instead.
func (*FileTransferCancel) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{12}
}

func (x *FileTransferCancel) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferCancel) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileTransferCancel) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type FileTransferDone struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	AgentId    string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Direction  string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	// status: "complete", "failed", or "canceled".
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Size           int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,7,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileTransferDone) Reset() {
	*x = FileTransferDone{}
	mi := &file_coc2_v1_wire_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferDone) ProtoMessage() {}

func (x *FileTransferDone) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferDone.ProtoReflect.Descriptor instead.
func (*FileTransferDone) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{13}
}

func (x *FileTransferDone) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferDone) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileTransferDone) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FileTransferDone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileTransferDone) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileTransferDone) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileTransferDone) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *FileTransferDone) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_coc2_v1_wire_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coc2_v1_wire_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_coc2_v1_wire_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_coc2_v1_wire_proto protoreflect.FileDescriptor

const file_coc2_v1_wire_proto_rawDesc = "" +
	"\n" +
	"\x12coc2/v1/wire.proto\x12\acoc2.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\fWireEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xcc\x02\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x19\n" +
	"\bip_addrs\x18\x06 \x03(\tR\aipAddrs\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12 \n" +
	"\vfingerprint\x18\b \x01(\tR\vfingerprint\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x12=\n" +
	"\fconnected_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12#\n" +
	"\rproto_version\x18\v \x01(\rR\fprotoVersion\"\x96\x01\n" +
	"\bHelloAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x122\n" +
	"\rpending_tasks\x18\x03 \x03(\v2\r.coc2.v1.TaskR\fpendingTasks\"`\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd8\x02\n" +
	"\rMetricsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vuptime_secs\x18\x03 \x01(\x03R\n" +
	"uptimeSecs\x12\x1b\n" +
	"\tcpu_count\x18\x04 \x01(\x05R\bcpuCount\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x05 \x01(\x05R\n" +
	"goroutines\x120\n" +
	"\x14process_memory_bytes\x18\x06 \x01(\x04R\x12processMemoryBytes\x121\n" +
	"\x15root_disk_total_bytes\x18\a \x01(\x04R\x12rootDiskTotalBytes\x12/\n" +
	"\x14root_disk_free_bytes\x18\b \x01(\x04R\x11rootDiskFreeBytes\"\xd9\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x04 \x01(\fR\acommand\x12!\n" +
	"\ftimeout_secs\x18\x05 \x01(\x05R\vtimeoutSecs\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"z\n" +
	"\aTaskAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"\x7f\n" +
	"\n" +
	"TaskCancel\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12=\n" +
	"\frequested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\x85\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\fR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xe0\x02\n" +
	"\x11FileTransferStart\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"local_path\x18\x04 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x05 \x01(\tR\n" +
	"remotePath\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\a \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\b \x01(\x05R\tchunkSize\x12'\n" +
	"\x0fchecksum_sha256\x18\t \x01(\tR\x0echecksumSha256\x12=\n" +
	"\frequested_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"Z\n" +
	"\x11FileTransferChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"h\n" +
	"\x12FileTransferResume\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\x8f\x01\n" +
	"\x12FileTransferCancel\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12=\n" +
	"\frequested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\x9a\x02\n" +
	"\x10FileTransferDone\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12'\n" +
	"\x0fchecksum_sha256\x18\a \x01(\tR\x0echecksumSha256\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"<\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x1eZ\x1ccoc2/internal/protocol/pb;pbb\x06proto3"

var (
	file_coc2_v1_wire_proto_rawDescOnce sync.Once
	file_coc2_v1_wire_proto_rawDescData []byte
)

func file_coc2_v1_wire_proto_rawDescGZIP() []byte {
	file_coc2_v1_wire_proto_rawDescOnce.Do(func() {
		file_coc2_v1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coc2_v1_wire_proto_rawDesc), len(file_coc2_v1_wire_proto_rawDesc)))
	})
	return file_coc2_v1_wire_proto_rawDescData
}

var file_coc2_v1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_coc2_v1_wire_proto_goTypes = []any{
	(*WireEnvelope)(nil),          // 0: coc2.v1.WireEnvelope
	(*AgentHello)(nil),            // 1: coc2.v1.AgentHello
	(*HelloAck)(nil),              // 2: coc2.v1.HelloAck
	(*Heartbeat)(nil),             // 3: coc2.v1.Heartbeat
	(*MetricsReport)(nil),         // 4: coc2.v1.MetricsReport
	(*Task)(nil),                  // 5: coc2.v1.Task
	(*TaskAck)(nil),               // 6: coc2.v1.TaskAck
	(*TaskCancel)(nil),            // 7: coc2.v1.TaskCancel
	(*TaskResult)(nil),            // 8: coc2.v1.TaskResult
	(*FileTransferStart)(nil),     // 9: coc2.v1.FileTransferStart
	(*FileTransferChunk)(nil),     // 10: coc2.v1.FileTransferChunk
	(*FileTransferResume)(nil),    // 11: coc2.v1.FileTransferResume
	(*FileTransferCancel)(nil),    // 12: coc2.v1.FileTransferCancel
	(*FileTransferDone)(nil),      // 13: coc2.v1.FileTransferDone
	(*ErrorMessage)(nil),          // 14: coc2.v1.ErrorMessage
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_coc2_v1_wire_proto_depIdxs = []int32{
	15, // 0: coc2.v1.AgentHello.connected_at:type_name -> google.protobuf.Timestamp
	15, // 1: coc2.v1.HelloAck.server_time:type_name -> google.protobuf.Timestamp
	5,  // 2: coc2.v1.HelloAck.pending_tasks:type_name -> coc2.v1.Task
	15, // 3: coc2.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	15, // 4: coc2.v1.MetricsReport.timestamp:type_name -> google.protobuf.Timestamp
	15, // 5: coc2.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: coc2.v1.TaskAck.received_at:type_name -> google.protobuf.Timestamp
	15, // 7: coc2.v1.TaskCancel.requested_at:type_name -> google.protobuf.Timestamp
	15, // 8: coc2.v1.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	15, // 9: coc2.v1.FileTransferStart.requested_at:type_name -> google.protobuf.Timestamp
	15, // 10: coc2.v1.FileTransferCancel.requested_at:type_name -> google.protobuf.Timestamp
	15, // 11: coc2.v1.FileTransferDone.completed_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_coc2_v1_wire_proto_init() }
func file_coc2_v1_wire_proto_init() {
	if File_coc2_v1_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coc2_v1_wire_proto_rawDesc), len(file_coc2_v1_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coc2_v1_wire_proto_goTypes,
		DependencyIndexes: file_coc2_v1_wire_proto_depIdxs,
		MessageInfos:      file_coc2_v1_wire_proto_msgTypes,
	}.Build()
	File_coc2_v1_wire_proto = out.File
	file_coc2_v1_wire_proto_goTypes = nil
	file_coc2_v1_wire_proto_depIdxs = nil
}
